:Title: OGC Features and Geometries JSON Standards Working Group Charter
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: <yyyy-mm-dd>
|Approval Date:   <yyyy-mm-dd>
|Internal reference number of this OGC(R) document:    YY-nnnrx
|Category: OGC(R) Standards Working Group Charter
|Authors:   Clemens Portele, Panagiotis (Peter) Vretanos, Scott Simmons
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2020 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<
////
Version of 2018-12-12
Some Instructions
This document is the template to be used for proposing the formation of a new Standards Working Group (SWG).

The first step is to complete the SWG Charter for the proposed new SWG.

The next step is to email the draft SWG charter to the Technical Committee Chair (TCC).  The TCC will review the draft charter and make any necessary comments and provide guidance.

Finally, once the Charter is ready, the SWG charter will be posted to the OGC Pending Documents and the vote process in the Technical Committee Policies and Procedures will start.

Any questions, please contact OGC staff.
////

To: OGC members & interested parties

A new OGC Standards Working Group (SWG) is being formed. The OGC members listed below have proposed the OGC Features and Geometries JSON SWG.  The SWG proposal provided in this document meets the requirements of the OGC Technical Committee (TC) Policies and Procedures.

The SWG name, statement of purpose, scope, list of deliverables, audience, and language specified in the proposal will constitute the SWG's official charter. Technical discussions may occur no sooner than the SWG's first meeting.

This SWG will operate under the OGC IPR Policy. The eligibility requirements for becoming a participant in the SWG at the first meeting (see details below) are that:

* You must be an employee of an OGC member organization or an individual
member of OGC;

* The OGC member must have signed the OGC Membership agreement;

* You must notify the SWG chair of your intent to participate to the first meeting. Members may do so by logging onto the OGC Portal and navigating to the Observer page and clicking on the link for the SWG they wish to join and;

* You must attend meetings of the SWG. The first meeting of this SWG is at the time and date fixed below. Attendance may be by teleconference.

Of course, participants also may join the SWG at any time. The OGC and the SWG welcomes all interested parties.

Non-OGC members who wish to participate may contact us about joining the OGC. In addition, the public may access some of the resources maintained for each SWG: the SWG public description, the SWG Charter, Change Requests, and public comments, which will be linked from the SWG’s page.

Please feel free to forward this announcement to any other appropriate lists. The OGC is an open standards organization; we encourage your feedback.

== Purpose of the Standards Working Group

////
Proposers will describe the purpose of the Standards Working Group and its overall mission in relation to OGC processes, the OGC standards baseline, and OGC’s business plan.
////

The OGC Features and Geometries JSON SWG is chartered to develop a JSON encoding for geospatial feature data. This encoding is intended to build upon the foundational OGC standards (such as Simple Features), be inclusive of other geospatial JSON encodings (such as GeoJSON [<<gj,1>>]), and support content delivery per the OGC API suite of standards. More specifically, OGC Features and Geometries JSON will build on the widely used GeoJSON standard and extend it with minimal extensions to support additional concepts that are important for the wider geospatial community and the OGC API standards. 

== Business Value Proposition

////
This section provides a statement describing the value of this standards activity in relation to the OGC Membership, the geospatial community, and the wider IT community. This statement can be in terms of the interoperability problem being solved, processing Change requests to meet market (and Member requirements), a policy requirement and/or some other business value proposition. The proposition described in this section does not have to be in economic terms.
////

JSON as an encoding format for geospatial data is becoming increasingly popular over XML. The light weight, simple syntax, and clear human and machine readability of JSON appeals to developers. GeoJSON has become a very popular encoding, but has significant limitations that prevent broad use in more technical circumstances. At a minimum, a more-inclusive JSON encoding for geospatial feature data should 

* include the ability to use Coordinate Reference Systems (CRSs) other than WGS84,
* support other non-Euclidean metrics, in particular ellipsoidal metrics,
* support more geometry types, in particular solids, and
* provide guidance on how to represent feature properties, including temporal properties, consistent with the General Feature Model in JSON.

In the future OGC Features and Geometries JSON may be extended include more complex geometries such as curves with non-linear interpolation, time-variant geometry or geometries based on multiple coordinate reference systems.

Given the popularity of GeoJSON, the SWG will ensure that OGC Features and Geometries JSON will be specified as a superset of GeoJSON so that valid GeoJSON is also valid OGC Features and Geometries JSON.

== Scope of Work

////
This section describes the scope of work (SOW) for the work of the SWG.

For a SWG focused on defining and documenting a new OGC candidate standard from “scratch,” the SOW SHALL include a statement of the requirements and use cases for the candidate standard being developed. The SOW SHALL also include a justification statement for developing a new candidate OGC standard. The SOW SHALL also describe how the new candidate standard is related to the existing OGC standards baseline and the OGC Reference Model. The final deliverable of a “from scratch” focused SWG SHALL be a candidate standard ready for submission using the OGC standards process.

In all cases, the SWG Charter shall provide a basic timeline plan for their activities.
////

OGC Features and Geometries JSON is intended to fulfill a known need in the geospatial and broader community for a JSON encoding of geospatial feature content that supports capabilities not found in GeoJSON, but which are generally more simple to implement than the OGC Geography Markup Language (GML)[<<gml,2>>]. The OGC Features and Geometries JSON SWG will consider the elements contributing to the Business Value Proposition (above) as general requirements for defining the encoding requirements. The SWG will take on the following work actions.

* Specify requirements for OGC Features and Geometries JSON based on the identified community needs and further consultation with members and users of geospatial data, such as the addition of CRS support.

* Use JSON Schema to specify the syntax of OGC Features and Geometries JSON.

* OGC Features and Geometries JSON will use a core-and-extensions approach. The initial task of the SWG will be the initial version of OGC Features and Geometries JSON and will be restricted to the requirements identified in this charter. If successful, the scope may be extended with tasks to support additional capabilities. 

* Leverage scope of profiles requested by the user community or domains to structure the design of the Standard such that profiling of the Standard is done by enumerating the conformance classes required by the community or domain.

* Assess relevance of JSON-LD[<<jl,3>>] to the structure of OGC Features and Geometries JSON.

* Use Sprints and/or Hackathons to help advance the work with realistic testing of the candidate Standard against community requirements.

* Register one or more media types for OGC Features and Geometries JSON with the OGC naming authority.

* Develop and move the candidate Standard through the approval process.

=== Statement of relationship of planned work to the current OGC standards baseline

////
This section describes the relationship of the proposed standards activity to the existing standards baseline. For the 3 cases:
If defining a new standard, a statement of the relationship to the existing standards baseline including statements related to overlap (if any) with existing OGC standards functionality, harmonization issues, and so forth.

If processing change requests and performing a revision to an existing standard, a simple statement to this effect shall be made.

If processing a draft submission of a specification developed outside the OGC process, a clear statement of the relationship to the existing standards baseline including statements related to overlap (if any) with existing OGC standards functionality, harmonization issues, and so forth. This information is provided to allow a focus of the discussion on criteria for considering any new solution that may be incompatible with older ones, overlaps existing functionality in the current baseline, and criteria for either deprecating older solutions, or simultaneously endorsing more than one option.
////

OGC Features and Geometries JSON will build upon existing OGC Standards and offer capabilities fulfilled in part (or in total) by other standards. The primary difference between this effort and other OGC standards is that OGC Features and Geometries JSON will provide a fundamental, yet flexible, encoding of geographic feature data in JSON.

* Simple Features[<<si1,4>>],[<<si2,5>>]: Simple Features provides a distinct set of geometric objects for describing geospatial feature data. Simple Feaures also defines the geometry model for most other OGC feature encodings.

* GML[<<gml,2>>]: GML is a comprehensive encoding of features, geometry and topology in XML. GML is quite heavy for simple feature data exchange and specifies an XML encoding for many other geospatial resources that are out-of-scope of this SWG such as coverage data or coordinate reference systems.

* GeoPackage[<<gp,6>>]: GeoPackage defines a container for geospatial data, including feature content. GeoPackage uses SQLite as a storage mechanism.

* KML[<<kml,7>>]: KML is an XML encoding of geographic features focused on its visualization including the control of the user's navigation in the sense of where to go and where to look.

* Abstract Specification Topic 1: Features and Geometry[<<fg,8>>]: OGC Abstract Specification Topic 1 is a comprehensive feature and geometry model from which Simple Features is derived.

* WKT CRS[<<wc,9>>]: The Well Known Text representation of Coordinate Reference Systems offers a standardized way to fully describe CRSs for reference by any spatial data set.

=== What is Out of Scope?

////
A short description of any activities that will be out of scope for the SWG. For example, a SWG may limit consideration of CRPs after a specified date or milestone.
////

OGC Features and Geometries JSON will not consider encodings beyond JSON.

Compatibility between versions of a standard is important. Revisions of OGC Features and Geometries JSON should avoid breaking existing implementations. Any Change Request that would result in a major revision of OGC Features and Geometries JSON is out-of-scope unless a 75% majority of the SWG members support the change.

Standards are important for interoperability. At the same time, it is important that standards only state requirements that are important for a significantly large group of users. Proposals for new tasks or change requests to an existing standard must identify the user groups that will benefit from the proposal and include the commitment for two independent implementations that will generate the proposed JSON and for two independent implementations that will consume the proposed JSON.

OGC Features and Geometries JSON is a modular standard. Developing profiles of OGC Features and Geometries JSON as separate standards should not be necessary and is, therefore, out-of-scope for the SWG. If a community has a need to develop a profile, the profile should be specified and governed by that community.

=== Specific Existing Work Used as Starting Point

////
This section provides reference information relevant to the work of the SWG. For example, a document reference for a draft submission or a list of CRPs for a SWG focused on revision to an adopted specification.
////

OGC Features and Geometries JSON will consider GeoJSON as a starting point for a content model and extend the model based on the benefits known from implementations of the Standards from the OGC Standards Baseline referenced above as well as other specifications used for geospatial data encoding and exchange.

The UGAS-2020 Pilot[<<up,10>>] has developed a proposal for a "Features Core Profile". If the Engineering Report will be approved by the OGC membership, it will be input to the work.

=== Is This a Persistent SWG

[x] YES

[ ] NO

=== When can the SWG be Inactivated

////
If this is not a persistent SWG, please define the criteria for determining when the SWG can be inactivated and the project archived. Please note that completion and archiving ensures that all files, wikis, emails, and so forth are archived and available for future viewing and use.
////

The SWG can be inactivated once the SWG identifies no new tasks for the SWG and there are no open Change Requests.

== Description of deliverables

////
This section describes what the deliverables will be for this SWG activity. Deliverables could be a revision to an existing standard, including revisions to schemas. A deliverable could also be a best practices document.

This section also includes a preliminary schedule of activities. For example, an RFC focused SWG schedule would provide a plan and schedule that includes the start date, target date for release of the candidate standard for public review, date for consolidation of comments, date for edits to document based on comments, and a final target date for making a recommendation to the Membership. This information will be made public and will also be used as input to a RoadMap for the document. Therefore, the more detail the better.
////

=== Initial Deliverables

////
Describe the initial standard(s) to be developed by the SWG.
////

The following deliverables will be the initial results of work of the SWG.

* OGC Features and Geometries JSON Standard.

* Associated implementation guidance for OGC Features and Geometries JSON.

* Any sample code, evidence of implementation, and/or compliance tests that might be developed in parallel to the Standard.

The targeted start date for this SWG is the first quarter of 2021, once the charter is approved. The SWG will aim to deliver an initial release of the candidate Standard for review by the end of 2021.

=== Additional SWG Tasks

////
Describe each additional standard to be developed by the SWG as an additional task after the deliverables from the initial charter have been completed. This section is blank in a new charter, then is populated with each task approval request per the OGC TC Policies and Procedures.
////

No specific additional tasks are currently planned for the SWG, although extension to the Standard may be considered in the future.

== IPR Policy for this SWG

[x] RAND-Royalty Free

[ ] RAND for fee

== Anticipated Audience / Participants

////
Description of the target participants in this SWG. For example, if the SWG were focused on a candidate spatial query language standard: Those involved in the design, development, implementation, or use of elements listed above in "Scope of the Work".  This includes search service providers, prospective users of search services exposed as XML, information architects and bibliographic, metadata, and content provider.

This is not meant as a limiting statement but instead is intended to provide guidance to interested potential participants as to whether they wish to participate in this SWG.
////

This SWG will develop a Standard for general use in the geospatial community and suitable for data exchange beyond this community. Geospatial data providers and software implementers will be interested in assisting with the development of this Standard as well as the output of the SWG.

== Domain Working Group Endorsement

////
The SWG will list all Domain Working Groups (DWGs) in which the SWG formation was discussed and/or chartered. If a DWG has specifically endorsed the formation of the SWG, then a statement of endorsement should be included.
////

This draft charter will be presented to the Architecture DWG with a request for endorsement.

== Other informative information about the work of this SWG

=== Collaboration

////
Describe the work environment of the SWG, including the use of GitHub or GitLab.
////

All work in the Standards Working Group will be public and the SWG solicits contributions and feedback from OGC members and non-OGC members to the extent that is supported by the OGC Technical Committee Policies and Procedures.

The OGC Features and Geometries JSON SWG will collaborate on Standard development using a public GitHub repository and a Gitter channel. Development of the Standard will include the use of Issues and other project tools in GitHub.

=== Similar or Applicable Standards Work (OGC and Elsewhere)

////
The following standards and projects may be relevant to the SWG's planned work, although none currently provide the functionality anticipated by this committee's deliverables:

OASIS BPEL
IETF HTTP

The SWG intends to seek and if possible maintain liaison with each of the organizations maintaining the above works.
////

GeoJSON is clearly related to this work and is planned to be a valid profile of the resulting OGC Standard.

=== Details of first meeting

////
Example:
The first meeting of the SWG will be held by telephone conference call at 10AM EDT on 1 October 2007. Call-in information will be provided to the SWG's e-mail list and on the portal calendar in advance of the meeting.
////

The first meeting of the SWG will occur within four weeks of approval of the SWG charter.

=== Projected on-going meeting schedule

////
Example:
The work of the SWG will be carried out primarily by email and conference calls, possibly every two weeks, with face-to-face meetings perhaps at each of the OGC TC meetings.
////

The work of this SWG will be carried out primarily on GitHub and via email, web conferences / calls, and at face-to-face sessions at OGC Member Meetings as agreed to by the SWG members. The web conferences / calls will be scheduled as needed and posted to the OGC portal. Voting on OGC Features and Geometries JSON content will be limited to SWG members only.

=== Supporters of this Charter

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter members. The charter members agree to the SoW and IPR terms as defined in this charter. The charter members have voting rights beginning the day the SWG is officially formed. Charter Members are shown on the public SWG page.

|===
|Name |Organization

|Clemens Portele |interactive instruments
|Panagiotis (Peter) A. Vretanos |CubeWerx Inc.
|===

=== Conveners

////
Name of individual(s) who started the SWG process. Could be the lead for an RFC submission, an OGC staff person, or an individual who believes it is time for a revision to an adopted standard.
////

Clemens Portele, Panagiotis (Peter) A. Vretanos

[bibliography]
== References

////
Optional list of references.
////

- [[[gj,1]]] IETF: IETF RFC 7946, The GeoJSON Format, 2016

- [[[gml,2]]] OGC: OGC 07-036r1, OpenGIS Geography Markup Language (GML) Encoding Standard 3.2.2, 2016

- [[[jl,3]]] W3C: JSON-LD A JSON-based Serialization for Linked Data, 2020

- [[[si1,4]]] OGC: OGC 06-103r4, OpenGIS Implementation Standard for Geographic information - Simple feature access - Part 1: Common architecture, 2011

- [[[si2,5]]] OGC: OGC 06-104r4, OpenGIS Implementation Standard for Geographic information - Simple feature access - Part 2: SQL option, 2010

- [[[gp,6]]] OGC: OGC 12-128r15, OGC GeoPackage Encoding Standard, 2018

- [[[kml,7]]] OGC: OGC 12-007r2, OGC KML 2.3, 2015

- [[[fg,8]]] OGC: OGC 17-087r13, OGC Abstract Specification Topic 1 Features and geometry – Part 1: Feature models, 2020

- [[[wc,9]]] OGC: OGC 18-010r7, Geographic information — Well-known text representation of coordinate reference systems, 2019

- [[[up,10]]] OGC: OGC 20-012, UML-to-GML Application Schema Pilot (UGAS-2020) Engineering Report, to-be-published (http://docs.opengeospatial.org/DRAFTS/20-012.html[draft])
